# Form implementation generated from reading ui file 'd:\Project_2025_fall_smart_todo_list\src\smart_todo_list\ui\tasks_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TasksWindow(object):
    def setupUi(self, TasksWindow):
        TasksWindow.setObjectName("TasksWindow")
        TasksWindow.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(TasksWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.taskTable = QtWidgets.QTableWidget(parent=TasksWindow)
        self.taskTable.setColumnCount(3)
        self.taskTable.setHorizontalHeaderLabels(['Название', 'Описание', 'Статус'])
        self.taskTable.setObjectName("taskTable")
        self.taskTable.setRowCount(0)
        self.verticalLayout.addWidget(self.taskTable)
        self.refreshButton = QtWidgets.QPushButton(parent=TasksWindow)
        self.refreshButton.setObjectName("refreshButton")
        self.verticalLayout.addWidget(self.refreshButton)

        self.retranslateUi(TasksWindow)
        QtCore.QMetaObject.connectSlotsByName(TasksWindow)

    def retranslateUi(self, TasksWindow):
        _translate = QtCore.QCoreApplication.translate
        TasksWindow.setWindowTitle(_translate("TasksWindow", "Список задач"))
        self.refreshButton.setText(_translate("TasksWindow", "Обновить список"))
