# Form implementation generated from reading ui file 'd:\Project_2025_fall_smart_todo_list\src\smart_todo_list\ui\tasks_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TasksWindow(object):
    def setupUi(self, TasksWindow):
        TasksWindow.setObjectName("TasksWindow")
        TasksWindow.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(TasksWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hideCompletedCheckBox = QtWidgets.QCheckBox(parent=TasksWindow)
        self.hideCompletedCheckBox.setObjectName("hideCompletedCheckBox")
        self.verticalLayout.addWidget(self.hideCompletedCheckBox)
        self.taskTable = QtWidgets.QTableWidget(parent=TasksWindow)
        self.taskTable.setColumnCount(3)
        self.taskTable.setRowCount(0)
        self.taskTable.setObjectName("taskTable")
        item = QtWidgets.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.taskTable)
        self.pushButtonAddTask = QtWidgets.QPushButton(parent=TasksWindow)
        self.pushButtonAddTask.setObjectName("pushButtonAddTask")
        self.verticalLayout.addWidget(self.pushButtonAddTask)

        self.retranslateUi(TasksWindow)
        QtCore.QMetaObject.connectSlotsByName(TasksWindow)

    def retranslateUi(self, TasksWindow):
        _translate = QtCore.QCoreApplication.translate
        self.hideCompletedCheckBox.setText(_translate("TasksWindow", "Скрыть выполненные"))
        item = self.taskTable.horizontalHeaderItem(0)
        item.setText(_translate("TasksWindow", "Название"))
        item = self.taskTable.horizontalHeaderItem(1)
        item.setText(_translate("TasksWindow", "Описание"))
        item = self.taskTable.horizontalHeaderItem(2)
        item.setText(_translate("TasksWindow", "Статус"))
        self.pushButtonAddTask.setText(_translate("TasksWindow", "Добавить задачу"))
