# Form implementation generated from reading ui file 'd:\Project_2025_fall_smart_todo_list\src\smart_todo_list\ui\welcome_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WelcomeWindow(object):
    def setupUi(self, WelcomeWindow):
        WelcomeWindow.setObjectName("WelcomeWindow")
        WelcomeWindow.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(WelcomeWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=WelcomeWindow)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.subtitleLabel = QtWidgets.QLabel(parent=WelcomeWindow)
        self.subtitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.verticalLayout.addWidget(self.subtitleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.loginButton = QtWidgets.QPushButton(parent=WelcomeWindow)
        self.loginButton.setMinimumSize(QtCore.QSize(0, 40))
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout.addWidget(self.loginButton)
        self.registerButton = QtWidgets.QPushButton(parent=WelcomeWindow)
        self.registerButton.setMinimumSize(QtCore.QSize(0, 40))
        self.registerButton.setObjectName("registerButton")
        self.verticalLayout.addWidget(self.registerButton)

        self.retranslateUi(WelcomeWindow)
        QtCore.QMetaObject.connectSlotsByName(WelcomeWindow)

    def retranslateUi(self, WelcomeWindow):
        _translate = QtCore.QCoreApplication.translate
        self.titleLabel.setText(_translate("WelcomeWindow", "Список дел 0.0"))
        self.subtitleLabel.setText(_translate("WelcomeWindow", "Выберите действие:"))
        self.loginButton.setText(_translate("WelcomeWindow", "Войти"))
        self.registerButton.setText(_translate("WelcomeWindow", "Зарегистрироваться"))
